version: '3.1'

services:

    db:
        image: recordexpungpdx:database
        env_file:
            - config/postgres/postgres.env
        volumes:
            - database_storage:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    expungeservice:
        image: recordexpungpdx:expungeservice
        env_file:
            - config/expungeservice/expungeservice.env
        ports:
            - "5000:5000"
        depends_on:
            - db
        volumes:
            - ./src/backend/tests:/var/www/tests

    webserver:
        image: recordexpungpdx:webserver
        ports:
            - "3000:3000"
